apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-groups-exporter-deployment
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: jupyterhub-groups-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion}}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jupyterhub-groups-exporter
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/name: jupyterhub-groups-exporter
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion}}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: jupyterhub-groups-exporter
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "-m", "jupyterhub_groups_exporter.groups_exporter"]
          args: [{{- if .Values.config.groupsExporter.allowed_groups }}"--allowed_groups", {{- range .Values.config.groupsExporter.allowed_groups }}"{{- join "," . }}",{{- end }}{{- end }}{{- if .Values.config.groupsExporter.double_count }}"--double_count", "{{ quote .Values.config.groupsExporter.double_count }}",{{- end }}--port, "{{ .Values.service.port }}", "--update_exporter_interval", "{{ .Values.config.groupsExporter.update_exporter_interval }}", "--log_level", "{{ .Values.config.groupsExporter.log_level }}"]
          env:
            {{- with .Values.extraEnv }}
            {{- tpl (. | toYaml) $ | nindent 12 }}
            {{- end }}
            - name: NAMESPACE
              value: {{ .Release.Name }}            
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
